// Auto-generated from the signed agreement source documents.
// Plain-text agreement bodies rendered by MembershipAgreementBody.

export const SILVER_PLUS_AGREEMENT: string[] = [
  "DIMES ONLY WORLD / HOUSING ANGELS, LLC",
  "SILVER PLUS MEMBERSHIP AGREEMENT",
  "This Silver Plus Membership Agreement (the “Agreement”) is entered into as of the date of the last signature below (the “Effective Date”), by and between Housing Angels, LLC, an Arizona limited liability company doing business as Dimes Only World (the “Company”), and the individual identified in the signature block below (the “Member”).",
  "The Company operates a premium membership, lifestyle, and earning platform known as Dimes Only World. The Member is a Silver Member (male or regular female) and desires to upgrade to a limited Silver Plus profit-sharer position and to participate in the Company’s referral, content, event, and profit-sharing programs, subject to the terms of this Agreement.",
  "NOW, THEREFORE, in consideration of the mutual promises herein, the Parties agree as follows:",
  "1. NATURE OF THE RELATIONSHIP",
  "1.1 This Agreement creates a membership relationship, not an employment, partnership, joint-venture, or agency relationship. The Member is an independent participant on the platform. Nothing in this Agreement makes the Member an employee or owner of the Company.",
  "1.2 Newly registered males, regular females, and similarly classified members start as Silver Members. Silver is the base membership. Silver Plus is a limited, upgraded profit-sharer position.",
  "1.3 Silver Plus is not automatic. It must be separately elected, paid (unless expressly gifted in writing), accepted by the Company, and available at the time of upgrade.",
  "1.4 Early access, complimentary Silver Membership, or promotional grants do not guarantee Silver Plus, profit sharing, or any particular income.",
  "2. ELIGIBILITY, IDENTITY, AND GOOD STANDING",
  "2.1 The Member represents that they are at least eighteen (18) years of age (or the age of majority in their jurisdiction, if higher), that all registration information is true and complete, and that they have the legal right to participate on the platform.",
  "2.2 The Company may require identity verification before issuing membership credentials, activating payouts, or confirming a Silver Plus seat. The Member agrees to keep all profile and payout information accurate.",
  "2.3 The Company may deny, suspend, or revoke Silver Plus status for false information, policy violations, legal risk, or conduct inconsistent with brand standards.",
  "3. SILVER MEMBERSHIP BENEFITS (BASE)",
  "Subject to good standing and platform rules, a Silver Member receives:",
  "Silver-level platform access",
  "The ability to build a referral / Money Circle network",
  "Access to platform features then available to Silver Members",
  "Status displayed as Silver Member until an accepted upgrade to Silver Plus",
  "Base Silver does not include the profit-share rights in Section 5.",
  "4. SILVER PLUS BENEFITS",
  "If the Member’s Silver Plus upgrade is accepted while a position remains open, the Member receives, subject to good standing:",
  "All Silver benefits",
  "Lifetime access to clubs, mansion parties, concerts, yacht parties, comedy shows, and other member events as available and subject to capacity, venue rules, and invitation or ticket terms",
  "Exclusive Silver-level content",
  "Priority support",
  "Member-only events",
  "Eligibility for Silver Plus profit sharing under Section 5",
  "Referral and override rights under Section 6, including the right to be paid on qualifying performer referrals as an upgraded member",
  "Event access and third-party experiences are privileges, not guaranteed property rights.",
  "5. SILVER PLUS PROFIT SHARING",
  "5.1 The Company has designated the first three hundred (300) males and/or regular females who upgrade to Silver Plus as the initial Silver Plus profit-share class. Those accepted positions are intended to receive up to $75,000 per year maximum, paid quarterly at up to $18,750 maximum, from the Company’s profit-share pool, if and when profit sharing is activated under this Section.",
  "5.2 Profit sharing is designed to begin when all of the following have occurred: (a) 300 strippers/exotic females have upgraded to Diamond Plus; (b) 300 males and/or regular females have upgraded to Silver Plus; and (c) 100 business owners have upgraded to Elite Plus (700 Plus positions in the initial class). After those 700 upgrades, Tier 1 profit sharing is intended to begin.",
  "5.3 When the Company later reaches a separately announced revenue threshold, Tier 2 is intended to activate for the profit-share class, with a stated target of at least $1,170,000 per year from the minimum revenue per quarter that triggers Tier 2. If Company revenue later falls below that threshold, Tier 1 is intended to reactivate.",
  "5.4 Profit-share amounts are maximums in tier 1 and miniimums in tier 2, not guaranteed salaries. Actual distributions depend on Company profits, the size of the pool, the number of active Plus members in good standing, and the Company’s written distribution rules at the time of payout. Nothing in this Agreement is a promise of a specific dollar amount in any quarter.",
  "5.5 Profit-share distributions, if any, are paid quarterly and only while the Member remains an active Silver Plus member in good standing. They are in addition to referral commissions, overrides, tips, app interactions, and other platform earnings.",
  "5.6 Silver Plus positions are strictly limited. Once filled, they are gone. The Member must upgrade before the app launches or before the designated positions are filled, whichever occurs first, unless the Company later opens additional classes in writing.",
  "5.7 Profit sharing is a contractual membership benefit. It is not stock, equity, a security offering, or a right to manage the Company. The Member has no voting rights and no claim to Company assets beyond distributions the Company actually declares under this Agreement.",
  "6. REFERRALS, OVERRIDES, AND MONEY CIRCLE",
  "6.1 The Member may refer other persons to the platform. Subject to the then-current referral rules and good standing:",
  "20% referral fee on all transactions until app release",
  "10% referrral fee overrides on qualifying second-level referral transactions",
  "6.2 To be paid on referrals of strippers or exotic females, the Member must hold an upgraded Plus membership (Silver Plus). Base Silver members may still refer, but performer-referral payouts require the upgrade.",
  "6.3 Referral fees may increase after the full app is released, as the Company announces in writing.",
  "6.4 Commissions are calculated only on qualifying, collected revenue and may be adjusted for refunds, chargebacks, failed payments, fraud, or policy violations. Installment payments generate corresponding installment commissions when actually received.",
  "6.5 The Money Circle is the Member’s visible network. Activity inside the circle may generate residual commissions when people in that circle generate qualifying revenue.",
  "7. FEES",
  "7.1 Silver Membership is the default starting status for males and regular females. The Silver Plus upgrade fee is a one-time fee unless the Company states otherwise in writing.",
  "7.2 Fees are generally non-refundable except where required by law or where the Company has published a specific refund window in writing. Platform use after purchase constitutes acceptance of the applicable fee terms.",
  "8. CONTENT AND INTELLECTUAL PROPERTY",
  "8.1 The Member retains ownership of original content they upload (“Member Content”), subject to the license in this Section.",
  "8.2 The Member grants the Company a worldwide, royalty-free, sublicensable license to host, display, promote, and distribute Member Content on the platform and in related marketing for so long as the account exists and for a reasonable wind-down period afterward.",
  "8.3 The Member represents that they own or control all rights in Member Content and that it does not violate law or third-party rights.",
  "8.4 Company names, logos, software, and trademarks remain Company property.",
  "9. CONDUCT AND BRAND STANDARDS",
  "The Member agrees to maintain professional conduct consistent with the Dimes Only World brand; not to misrepresent earnings, membership status, or Company affiliation; not to harass, defraud, or exploit other members; and not to use the platform for any unlawful purpose. The Company may remove content, suspend features, or terminate membership for violations.",
  "10. CONFIDENTIALITY",
  "The Member shall not disclose non-public Company information, including member data, unpublished payout formulas, unreleased product plans, or internal communications. This duty survives termination for three (3) years, and longer for trade secrets.",
  "11. TERM, SUSPENSION, AND TERMINATION",
  "11.1 Silver Plus is intended to continue for the Member’s lifetime while the Member remains in good standing and the platform remains in operation.",
  "11.2 The Company may suspend or terminate this Agreement for material breach, fraud, chargebacks, illegal activity, false identity, or conduct that materially harms the brand or other members. The Member may terminate by written notice and closing the account.",
  "11.3 Upon termination, platform access ends. Accrued, earned, and undisputed commissions on already-collected qualifying revenue will be paid according to the regular payout cycle, less offsets. Unvested or unearned profit-share expectations expire. Sections 8, 9, 10, 12, 13, and 14 survive.",
  "12. TAXES AND PAYOUTS",
  "The Member is solely responsible for taxes on all amounts received. The Company may issue Form 1099-NEC or other required tax forms and may require a W-9 (or equivalent) before payout. The Member is an independent contractor with respect to commissions and profit-share distributions, not a Company employee.",
  "13. DISCLAIMERS",
  "THE PLATFORM, EVENTS, AND EARNING FEATURES ARE PROVIDED “AS IS.” THE COMPANY DOES NOT GUARANTEE ANY LEVEL OF INCOME, TIPS, REFERRALS, APP LAUNCH DATE, OR PROFIT-SHARE DISTRIBUTION. EXAMPLES USED IN MARKETING ARE ILLUSTRATIVE MAXIMUMS OR HYPOTHETICALS. THE MEMBER IS RESPONSIBLE FOR THEIR OWN RECRUITING, ACTIVITY, AND TAX COMPLIANCE. THE COMPANY IS NOT A BROKER-DEALER AND THIS AGREEMENT IS NOT AN OFFER OF SECURITIES.",
  "14. LIMITATION OF LIABILITY AND INDEMNITY",
  "To the maximum extent permitted by law, the Company’s total liability under this Agreement shall not exceed the membership or upgrade fees the Member actually paid to the Company in the twelve (12) months before the claim (or $500 if no fees were paid). The Company is not liable for indirect, incidental, or consequential damages. The Member shall indemnify the Company against claims arising from Member Content, the Member’s conduct, misrepresentations, or tax obligations.",
  "15. GOVERNING LAW",
  "This Agreement is governed by the laws of the State of Arizona, without regard to conflict-of-law rules. The Parties shall first attempt good-faith negotiation for fifteen (15) days. Thereafter, exclusive venue lies in the state or federal courts in Arizona.",
  "16. GENERAL TERMS",
  "This Agreement is the entire understanding regarding Silver Plus Membership and supersedes prior discussions on that subject. It may be amended only in a writing signed by the Company, or by updated online terms that the Member accepts by continued use after notice. If a provision is unenforceable, the remainder stays in force. The Member may not assign this Agreement without Company consent. Electronic signatures and counterparts are valid.",
  "IN WITNESS WHEREOF, the Parties have executed this Silver Plus Membership Agreement as of the Effective Date."
];

export const ELITE_PLUS_AGREEMENT: string[] = [
  "ELITE PLUS MEMBERSHIP AGREEMENT",
  "(Business Owner Profit-Sharer)",
  "This Elite Plus Membership Agreement (the “Agreement”) is entered into as of the date of the last signature below (the “Effective Date”), by and between Housing Angels, LLC, an Arizona limited liability company doing business as Dimes Only World (the “Company”), and the business owner / entity identified in the signature block below (the “Member”).",
  "The Company operates a premium membership, lifestyle, and earning platform known as Dimes Only World. The Member desires to obtain a limited Elite Plus profit-sharer position as a business owner and to participate in the Company’s referral, event, advertising, and profit-sharing programs, subject to the terms of this Agreement.",
  "NOW, THEREFORE, in consideration of the mutual promises herein, the Parties agree as follows:",
  "1. NATURE OF THE RELATIONSHIP",
  "1.1 This Agreement creates a membership / independent contractor relationship, not an employment, partnership, joint-venture, or agency relationship. Nothing in this Agreement makes the Member an employee, officer, or owner of the Company.",
  "1.2 Newly registered business owners start as Silver Members until they upgrade. Elite Plus is a limited, upgraded profit-sharer position reserved for business owners.",
  "1.3 Elite Plus is not automatic. It must be separately elected, paid, accepted by the Company, and available at the time of upgrade.",
  "1.4 Early access or promotional grants do not guarantee Elite Plus, profit sharing, county exclusivity, or any particular income.",
  "2. ELIGIBILITY AND GOOD STANDING",
  "2.1 The Member represents that they are at least eighteen (18) years of age (or the age of majority in their jurisdiction, if higher), that they have authority to bind the listed business entity (if any), and that all registration information is true and complete.",
  "2.2 The Company may require identity verification, entity documents, and a completed W-9 before activating payouts or confirming an Elite Plus seat.",
  "2.3 The Company may deny, suspend, or revoke Elite Plus status for false information, policy violations, legal risk, or conduct inconsistent with brand standards.",
  "3. ELITE PLUS BENEFITS",
  "If the Member’s Elite Plus upgrade is accepted while a position remains open, the Member receives, subject to good standing:",
  "All base membership access then available to business-owner members",
  "Eligibility for Elite Plus profit sharing under Section 5",
  "Referral and override rights under Section 6",
  "Priority support",
  "Member-only and business-owner events as available",
  "Access to events for the Member and up to three (3) guests, subject to availability",
  "Lifetime advertisement placement two (2) times per month, as inventory and brand standards allow",
  "Access to Housing Angels Reality Show cast/contestants at a fifty percent (50%) discount for walk-throughs at the Member’s establishment, subject to availability and talent consent",
  "Event access, advertising slots, and talent walk-throughs are privileges, not guaranteed property rights.",
  "4. OPTIONAL EXCLUSIVE COUNTY POSITION",
  "4.1 If the Member separately purchases an exclusive county profit-sharer package (currently a one-time fee of Fifteen Thousand United States Dollars ($15,000.00), unless otherwise stated in writing), the Company grants the Member an exclusive profit-sharer position within the geographic limits of the county named in the signature block.",
  "4.2 During the term of that exclusive position, the Company shall not enter into a similar profit-sharing, partnership, or membership agreement with any other strip club, gentlemen’s club, or comparable adult entertainment venue within those county limits.",
  "4.3 Exclusive county rights apply only if that package is purchased and accepted. Elite Plus alone does not create county exclusivity.",
  "4.4 Refund for the exclusive county package only: if the Member has not recouped the full $15,000 initial investment through earned overrides and profit sharing within six (6) months of the Effective Date of that package, the Member may submit a written request for a full refund. The request must be received within thirty (30) days after the six-month anniversary. After the 31st day following that six-month period, the refund option expires.",
  "5. ELITE PLUS PROFIT SHARING",
  "5.1 The Company has designated the first one hundred (100) business owners who upgrade to Elite Plus as the initial Elite Plus profit-share class. Those accepted positions are intended to receive up to $200,000 per year maximum, paid quarterly at up to $50,000 maximum, from the Company’s profit-share pool, if and when profit sharing is activated under this Section.",
  "5.2 Profit sharing is designed to begin when all of the following have occurred: (a) 300 strippers/exotic females have upgraded to Diamond Plus; (b) 300 males and/or regular females have upgraded to Silver Plus; and (c) 100 business owners have upgraded to Elite Plus (700 Plus positions in the initial class). After those 700 upgrades, Tier 1 profit sharing is intended to begin.",
  "5.3 When the Company later reaches a separately announced revenue threshold, Tier 2 is intended to activate for the profit-share class, with a stated target of at least $1,170,000 per year from the minimum revenue per quarter that triggers Tier 2. If Company revenue later falls below that threshold, Tier 1 is intended to reactivate.",
  "5.4 Profit-share amounts are maximums in tier 1 and miniimums in tier 2, not guaranteed salaries. Actual distributions depend on Company profits, the size of the pool, the number of active Plus members in good standing, and the Company’s written distribution rules at the time of payout. Nothing in this Agreement is a promise of a specific dollar amount in any quarter.",
  "5.5 Profit-share distributions, if any, are paid quarterly and only while the Member remains an active Elite Plus member in good standing. They are in addition to referral commissions, overrides, advertising value, and other platform earnings.",
  "5.6 Elite Plus positions are strictly limited to the first 100 business-owner upgrades in the initial class. Once filled, they are gone unless the Company later opens additional classes in writing.",
  "5.7 Profit sharing is a contractual membership benefit. It is not stock, equity, a security offering, or a right to manage the Company. The Member has no voting rights and no claim to Company assets beyond distributions the Company actually declares under this Agreement.",
  "6. REFERRALS, OVERRIDES, AND MONEY CIRCLE",
  "6.1 Subject to the then-current referral rules and good standing:",
  "20% referral fee on all transactions until app release",
  "10% referrral fee overrides on qualifying second-level referral transactions",
  "6.2 Overrides from females in the Member’s network are included in override calculations.",
  "6.3 Referral fees may increase after the full app is released, as the Company announces in writing.",
  "6.4 Commissions are calculated only on qualifying, collected revenue and may be adjusted for refunds, chargebacks, failed payments, fraud, or policy violations. Installment payments generate corresponding installment commissions when actually received.",
  "6.5 The Money Circle is the Member’s visible network. Activity inside the circle may generate residual commissions when people in that circle generate qualifying revenue.",
  "7. FEES",
  "7.1 The Elite Plus upgrade fee is a one-time fee as noted on this page, unless the Company states otherwise in writing. Any exclusive county package fee is separate.",
  "7.2 Except for the limited county-package refund in Section 4.4, fees are generally non-refundable except where required by law. Platform use after purchase constitutes acceptance of the applicable fee terms.",
  "8. INTELLECTUAL PROPERTY AND ADVERTISING",
  "8.1 Company names, logos, software, and trademarks remain Company property. The Member receives a limited, revocable license to use them only as needed to participate as an Elite Plus member and to display approved advertisements.",
  "8.2 Advertising creative submitted by the Member must meet Company brand standards and applicable law. The Company may refuse or remove ads that it reasonably determines are off-brand, unlawful, or harmful.",
  "9. CONDUCT AND BRAND STANDARDS",
  "The Member agrees to maintain professional standards consistent with the Dimes Only World brand; not to misrepresent earnings, exclusivity, or Company affiliation; and not to use the platform for any unlawful purpose. The Company may suspend features or terminate membership for violations.",
  "10. CONFIDENTIALITY",
  "The Member shall not disclose non-public Company information, including member data, unpublished payout formulas, unreleased product plans, or internal communications. This duty survives termination for three (3) years, and longer for trade secrets.",
  "11. TERM, SUSPENSION, AND TERMINATION",
  "11.1 Elite Plus is intended to continue for the lifetime of the Member’s ownership/operation of the listed establishment or business, while the Member remains in good standing and the platform remains in operation, unless ended earlier under this Agreement.",
  "11.2 Either Party may terminate this Agreement by written notice as follows: the Company may terminate immediately for cause (material breach, fraud, illegal activity, or conduct that materially harms the brand). Either Party may terminate without cause on fourteen (14) days’ written notice, except that an accepted exclusive county position continues for the Member’s ownership/operation of that establishment unless terminated for cause or by mutual written agreement.",
  "11.3 Upon termination, platform access and exclusivity end. Accrued, earned, and undisputed commissions on already-collected qualifying revenue will be paid according to the regular payout cycle, less offsets. Unvested or unearned profit-share expectations expire. Sections 8, 9, 10, 12, 13, and 14 survive.",
  "12. TAXES AND PAYOUTS",
  "The Member is solely responsible for taxes on all amounts received. The Company may issue Form 1099-NEC or other required tax forms and may require a W-9 before payout. The Member is an independent contractor with respect to commissions and profit-share distributions, not a Company employee.",
  "13. DISCLAIMERS",
  "THE PLATFORM, EVENTS, ADVERTISING, AND EARNING FEATURES ARE PROVIDED “AS IS.” THE COMPANY DOES NOT GUARANTEE ANY LEVEL OF INCOME, REFERRALS, APP LAUNCH DATE, FOOT TRAFFIC, OR PROFIT-SHARE DISTRIBUTION. EXAMPLES USED IN MARKETING ARE ILLUSTRATIVE MAXIMUMS OR HYPOTHETICALS. THE COMPANY IS NOT A BROKER-DEALER AND THIS AGREEMENT IS NOT AN OFFER OF SECURITIES.",
  "14. LIMITATION OF LIABILITY AND INDEMNITY",
  "To the maximum extent permitted by law, the Company’s total liability under this Agreement shall not exceed the fees the Member actually paid to the Company in the twelve (12) months before the claim. The Company is not liable for indirect, incidental, or consequential damages. The Member shall indemnify the Company against claims arising from the Member’s establishment, advertising, conduct, misrepresentations, or tax obligations.",
  "15. GOVERNING LAW",
  "This Agreement is governed by the laws of the State of Arizona, without regard to conflict-of-law rules. The Parties shall first attempt good-faith negotiation for fifteen (15) days. Thereafter, exclusive venue lies in the state or federal courts in Arizona.",
  "16. GENERAL TERMS",
  "This Agreement is the entire understanding regarding Elite Plus Membership and supersedes prior discussions on that subject. It may be amended only in a writing signed by the Company, or by updated online terms that the Member accepts by continued use after notice. If a provision is unenforceable, the remainder stays in force. The Member may not assign this Agreement without Company consent, except to a successor owner of the listed establishment with Company approval. Electronic signatures and counterparts are valid.",
  "IN WITNESS WHEREOF, the Parties have executed this Elite Plus Membership Agreement as of the Effective Date."
];
