project_id = "qkcuykpndrolrewwnkwb"

[functions.admin-data]
verify_jwt = false

[functions.public-data]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.authenticate-user]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.test-tip-allocation]
verify_jwt = false
