// This file is automatically generated. Do not edit it directly.
import { supabase as sharedSupabase } from '@/lib/supabase';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// IMPORTANT: Re-export the shared singleton from @/lib/supabase so the whole app
// uses ONE client with ONE storage key ('dimes-only-auth'). A second client with
// the default storage key races to consume auth URL tokens (e.g. password
// recovery links), which breaks the reset-password flow.
export const supabase = sharedSupabase;
