// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { supabase as sharedSupabase } from '@/lib/supabase';

const SUPABASE_URL = 'https://qkcuykpndrolrewwnkwb.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrY3V5a3BuZHJvbHJld3dua3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODIwNzAsImV4cCI6MjA2NDk1ODA3MH0.gamp40tIrDSMaI5_YMIrn3qCR-oVdx__YtvBl75yOJs';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// IMPORTANT: Re-export the shared singleton from @/lib/supabase so the whole app
// uses ONE client with ONE storage key ('dimes-only-auth'). A second client with
// the default storage key races to consume auth URL tokens (e.g. password
// recovery links), which breaks the reset-password flow.
export const supabase = sharedSupabase;
